spring.application.name=backend

# MySQL Configuration
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&tlsVersions=TLSv1.2,TLSv1.3
spring.datasource.username=54nUQSLS4KKQmk8.root
spring.datasource.password=advaitrd12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# JWT
jwt.secret=${JWT_SECRET:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}
jwt.expirationMs=86400000


# Twilio WhatsApp Configuration
twilio.account.sid=${TWILIO_ACCOUNT_SID:AC297dbc892ebeda1976dd15dcbbff6ab2}
twilio.auth.token=${TWILIO_AUTH_TOKEN:322bef13d6d0a604464d487685d64fb4}
twilio.whatsapp.number=${TWILIO_WHATSAPP_NUMBER:whatsapp:+14155238886}


# External API Keys (RapidAPI)
# Get your key from: https://rapidapi.com/
api.rapidapi.key=${RAPIDAPI_KEY:8a71fabe4emsh3fc7546bb50962dp1c51c4jsn28697b3b89f6}

# Individual Fallbacks (Optional)
api.tmdb.key=${TMDB_KEY:8a71fabe4emsh3fc7546bb50962dp1c51c4jsn28697b3b89f6}
api.ticketmaster.key=${TICKETMASTER_KEY:8a71fabe4emsh3fc7546bb50962dp1c51c4jsn28697b3b89f6}